# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uoNIXlRjNO3Hj-J5hwjrhFMqAcZoA4Es
"""

import streamlit as st
st.title("مرحبا 👋")
name=st.text_input("ادخل اسمك")
age=st.number_input("ادخل عمرك")
gender=st.selectbox("ولد ولا بنت",("male","female"))
st.write("اهلا بك يا ",name)
st.balloons()
st.snow()

